/*

 * To change this license header, choose License Headers in Project Properties.

 * To change this template file, choose Tools | Templates

 * and open the template in the editor.

 */

package UserInterface;



import BusinessLayer.*;



import javax.swing.JOptionPane;

//import static javax.swing.text.html.HTML.Tag.SELECT;



/**

 *

 * @author user

 */

public class LoginPage extends javax.swing.JFrame {

 public static String userName;

 UserManagement um = new UserManagement();

    /**

     * Creates new form Login

     */

    public LoginPage() {

        initComponents();

        this.setLocationRelativeTo(null);

    }



    /**

     * This method is called from within the constructor to initialize the form.

     * WARNING: Do NOT modify this code. The content of this method is always

     * regenerated by the Form Editor.

     */

    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

    private void initComponents() {



        jPanel1 = new javax.swing.JPanel();

        jLabel1 = new javax.swing.JLabel();

        jTextField1 = new javax.swing.JTextField();

        jLabel2 = new javax.swing.JLabel();

        AdminCheckBox = new javax.swing.JCheckBox();

        jPasswordField1 = new javax.swing.JPasswordField();

        jLabel3 = new javax.swing.JLabel();

        jPanel2 = new javax.swing.JPanel();

        jButton1 = new javax.swing.JButton();

        jButton2 = new javax.swing.JButton();



        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setTitle("Login");

        setBackground(new java.awt.Color(0, 51, 0));

        setForeground(java.awt.Color.darkGray);

        setLocation(new java.awt.Point(0, 0));

        setResizable(false);



        jPanel1.setBackground(new java.awt.Color(0, 51, 0));

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));



        jLabel1.setBackground(new java.awt.Color(0, 51, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("UserName");

        jLabel1.setName("lblUser"); // NOI18N



        jLabel2.setBackground(new java.awt.Color(0, 51, 0));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Password");



        AdminCheckBox.setBackground(new java.awt.Color(0, 51, 0));

        AdminCheckBox.setForeground(new java.awt.Color(255, 255, 255));

        AdminCheckBox.setText("Administrator");

        AdminCheckBox.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                AdminCheckBoxActionPerformed(evt);

            }

        });



        jLabel3.setBackground(new java.awt.Color(51, 0, 0));

        jLabel3.setFont(new java.awt.Font("Edwardian Script ITC", 1, 36)); // NOI18N

        jLabel3.setForeground(new java.awt.Color(255, 153, 51));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setText("Welcome");

        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);



        jPanel2.setBackground(new java.awt.Color(0, 51, 0));



        jButton1.setText("Login");

        jButton1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jButton1ActionPerformed(evt);

            }

        });



        jButton2.setText("Exit");

        jButton2.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jButton2ActionPerformed(evt);

            }

        });



        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);

        jPanel2.setLayout(jPanel2Layout);

        jPanel2Layout.setHorizontalGroup(

            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel2Layout.createSequentialGroup()

                .addGap(18, 18, 18)

                .addComponent(jButton1)

                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)

                .addComponent(jButton2)

                .addContainerGap())

        );

        jPanel2Layout.setVerticalGroup(

            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel2Layout.createSequentialGroup()

                .addGap(0, 0, 0)

                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                    .addComponent(jButton1)

                    .addComponent(jButton2))

                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

        );



        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);

        jPanel1.setLayout(jPanel1Layout);

        jPanel1Layout.setHorizontalGroup(

            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel1Layout.createSequentialGroup()

                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                    .addGroup(jPanel1Layout.createSequentialGroup()

                        .addGap(46, 46, 46)

                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                            .addComponent(jLabel1)

                            .addComponent(jLabel2))

                        .addGap(28, 28, 28)

                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

                            .addComponent(jTextField1)

                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))

                        .addGap(74, 74, 74)

                        .addComponent(AdminCheckBox))

                    .addGroup(jPanel1Layout.createSequentialGroup()

                        .addGap(141, 141, 141)

                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)

                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)

                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))

                .addContainerGap(68, Short.MAX_VALUE))

        );

        jPanel1Layout.setVerticalGroup(

            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addGroup(jPanel1Layout.createSequentialGroup()

                .addContainerGap()

                .addComponent(jLabel3)

                .addGap(39, 39, 39)

                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                    .addComponent(jLabel1)

                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

                    .addComponent(AdminCheckBox))

                .addGap(18, 18, 18)

                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

                    .addComponent(jLabel2)

                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))

                .addGap(76, 76, 76)

                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

                .addContainerGap(36, Short.MAX_VALUE))

        );



        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());

        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(

            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

        );

        layout.setVerticalGroup(

            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

        );



        pack();

        setLocationRelativeTo(null);

    }// </editor-fold>//GEN-END:initComponents



  

    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        

            if (jTextField1.getText().isEmpty() || jPasswordField1.getPassword().length == 0){
                JOptionPane.showMessageDialog(null,"Insert user name and password.");
            }else{
        if(AdminCheckBox.isSelected()== true){

       try

                {

                    boolean x = false;

                    x = um.checkAdmin(jTextField1.getText(), jPasswordField1.getText());

                    

                    if (x = false){

                        JOptionPane.showMessageDialog(null,"Incorrect UserName or Password");

                    }else{

                        AdministrationPage admin = new AdministrationPage();

                        admin.setVisible(true);

                         this.setVisible(false);

                    }

                                    

   

                             

                }

            catch(Exception ex){

                //JOptionPane.showMessageDialog(null,ex.getMessage());

            }

        }

        else{// if the user didn't check the admin check box this block will excute

            try

                {

                    boolean x = false;

                    x = um.checkUser(jTextField1.getText(), jPasswordField1.getText());

                   

                   if (x == false){

                        JOptionPane.showMessageDialog(null,"Incorrect UserName or Password");

                    }else{

                        SMEHomePage u = new SMEHomePage();

                         u.setVisible(true);

                         this.setVisible(false);

                         //break;

                     }

                   }

            catch(Exception ex){

                //JOptionPane.showMessageDialog(null,ex.getMessage());

            }

        }

        }

                

    }//GEN-LAST:event_jButton1ActionPerformed



    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:

        System.exit(0);

        

    }//GEN-LAST:event_jButton2ActionPerformed



    private void AdminCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminCheckBoxActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_AdminCheckBoxActionPerformed



    /**

     * @param args the command line arguments

     */

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.

         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 

         */

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;

                }

            }

        } catch (ClassNotFoundException ex) {

            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {

            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {

            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {

            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>



        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

               /* try{

                    Thread.sleep(4000);

                }

                catch(Exception e)

                {

                    

                }*/

                new LoginPage().setVisible(true);

            }

        });

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JCheckBox AdminCheckBox;

    private javax.swing.JButton jButton1;

    private javax.swing.JButton jButton2;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JPanel jPanel1;

    private javax.swing.JPanel jPanel2;

    private javax.swing.JPasswordField jPasswordField1;

    private javax.swing.JTextField jTextField1;

    // End of variables declaration//GEN-END:variables

}

